// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using VitalTrack.Data;

#nullable disable

namespace VitalTrack.Data.Migrations
{
    [DbContext(typeof(VitalTrackDbContext))]
    partial class VitalTrackDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VitalTrack.Data.Entities.User", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<int>("Age").HasColumnType("int");
                b.Property<string>("ActivityLevel").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<double>("BodyFatPercent").HasColumnType("float");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<string>("Email").IsRequired().HasMaxLength(150).HasColumnType("nvarchar(150)");
                b.Property<string>("FullName").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("Gender").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<double>("HeightCm").HasColumnType("float");
                b.Property<string>("PasswordHash").IsRequired().HasMaxLength(256).HasColumnType("nvarchar(256)");
                b.Property<string>("Role").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<DateTime>("UpdatedAt").HasColumnType("datetime2");
                b.Property<string>("Username").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<double>("WeightKg").HasColumnType("float");
                b.HasKey("Id");
                b.HasIndex("Username").IsUnique();
                b.HasIndex("Email").IsUnique();
                b.ToTable("Users");
            });

            modelBuilder.Entity("VitalTrack.Data.Entities.WorkoutSession", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<double>("CaloriesBurned").HasColumnType("float");
                b.Property<int>("DurationMinutes").HasColumnType("int");
                b.Property<string>("ExerciseName").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<DateTime>("LoggedAt").HasColumnType("datetime2");
                b.Property<string>("MuscleGroup").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("Notes").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<int>("Reps").HasColumnType("int");
                b.Property<int>("Sets").HasColumnType("int");
                b.Property<int>("UserId").HasColumnType("int");
                b.Property<double>("WeightKg").HasColumnType("float");
                b.HasKey("Id");
                b.HasIndex("UserId");
                b.ToTable("WorkoutSessions");
            });

            modelBuilder.Entity("VitalTrack.Data.Entities.NutritionLog", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<double>("Calories").HasColumnType("float");
                b.Property<double>("CarbsG").HasColumnType("float");
                b.Property<double>("FatG").HasColumnType("float");
                b.Property<string>("FoodName").IsRequired().HasMaxLength(150).HasColumnType("nvarchar(150)");
                b.Property<DateTime>("LoggedAt").HasColumnType("datetime2");
                b.Property<string>("MealType").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
                b.Property<double>("ProteinG").HasColumnType("float");
                b.Property<double>("ServingGrams").HasColumnType("float");
                b.Property<int>("UserId").HasColumnType("int");
                b.HasKey("Id");
                b.HasIndex("UserId");
                b.ToTable("NutritionLogs");
            });

            modelBuilder.Entity("VitalTrack.Data.Entities.ChatLog", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("BotResponse").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<string>("UserMessage").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<int>("UserId").HasColumnType("int");
                b.HasKey("Id");
                b.HasIndex("UserId");
                b.ToTable("ChatLogs");
            });

            modelBuilder.Entity("VitalTrack.Data.Entities.WorkoutSession", b =>
            {
                b.HasOne("VitalTrack.Data.Entities.User", "User")
                    .WithMany("WorkoutSessions")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("User");
            });

            modelBuilder.Entity("VitalTrack.Data.Entities.NutritionLog", b =>
            {
                b.HasOne("VitalTrack.Data.Entities.User", "User")
                    .WithMany("NutritionLogs")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("User");
            });

            modelBuilder.Entity("VitalTrack.Data.Entities.ChatLog", b =>
            {
                b.HasOne("VitalTrack.Data.Entities.User", "User")
                    .WithMany("ChatLogs")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("User");
            });

            modelBuilder.Entity("VitalTrack.Data.Entities.User", b =>
            {
                b.Navigation("WorkoutSessions");
                b.Navigation("NutritionLogs");
                b.Navigation("ChatLogs");
            });
#pragma warning restore 612, 618
        }
    }
}
